# Generated by Django 3.2.9 on 2021-12-01 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_barber_cosmetic_haircut'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmetic',
            name='boxer',
            field=models.CharField(default='box', max_length=10, verbose_name='Дизайн бокса'),
        ),
    ]
